version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: github.com/yagoayala/golang-graphql-api
    container_name: golang-graphql-api
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: website
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/golang-graphql-api
    volumes:
      - golang-graphql-api:/var/lib/postgresql/data

volumes:
  golang-graphql-api: